CREATE TABLE IF NOT EXISTS USERNAME_LIST (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RESTRICTED_WORDS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	WORD VARCHAR NOT NULL
);
